#!/usr/bin/env bash
# Bash script that generates the AUTHOR file in the project's root directory

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(git -C "$SCRIPTDIR" rev-parse --show-toplevel)"

set -x

# see also ".mailmap" for how email addresses and names are deduplicated
cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File @generated by scripts/generate-authors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See scripts/generate-authors.sh to make modifications.

	# These individuals contributed to the hbnb project in this repository

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
